apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: schoolofdevops/voterrrrrrr:v3
        name: vote
        envFrom:
          - configMapRef:
              name: vote-options
              optional: true

