apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 1
images:
  - name: schoolofdevops/vote
newTag: v6
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@morinhun.org"
configMapGenerator:
  - name: vote-options
    env: options.env
